### ISSUE TITLE
UI Komponent | Nazwa trybu gry

### ISSUE THREAD

**Issue by pspaczek** [pspaczek/CodersCamp2020JavaScript#11]
### Kryteria akceptacji
**Należy zweryfikować i skonsultować, a także ewentualnie uaktualnić przed rozpoczęciem prac nad zgłoszeniem.**

- [x]  Komponent zdefiniowany w odrębnym pliku .js
- [x]  Komponent przyjmuje na wejściu opisową nazwę trybu gry, np. 'Who is this character?'
- [x]  Komponent wyświetla przekazany napis po napisie MODE.
- [ ]  Działanie komponentu zostało pokryte testami jednostkowymi.
- [x]  Wygląd komponentu wg. projektu:
![97785221-f345f700-1ba3-11eb-840f-23638ca3ab41](https://user-images.githubusercontent.com/12138170/103749516-e27f8a80-5005-11eb-9d22-78a2ca2537e2.png)

**Comment by ZibiH** [comment]
Component finished
